# Generated by Django 4.2.2 on 2023-06-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_comment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upload_date',
            field=models.DateTimeField(default='1233-01-23'),
            preserve_default=False,
        ),
    ]
